# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# andy = User.create(name: "Andy", email: "andy@lhl.com")
egg = User.create(name: "Egg Eggerson", email: "egg@egg.com")
spock = User.create(name: "Spock", email: "spock@vulcan.com")
boromir = User.create(name: "Boromir", email: "boromir@gondor.com")
faramir = User.create(name: "Faramir", email: "faramir@daddyissues.com")
geraldo = User.create(name: "Geraldo", email: "geraldo@riverdale.com")

javascript_project = Project.create(name: "Javascript Learning Resources", description: "Cool Educational Resources", user: egg)
spock_project = Project.create(name: "Star Trek Fanfiction", description: "sources for star trek fanfiction", user: spock)
boromir_project = Project.create(name: "Military History of Agincourt", description: "reasearching the battle of agincourt", user: boromir)
faramir_project = Project.create(name: "Lord of the Rings Fanfiction", description: "sources for lord of the rings fanfiction", user: faramir)
# geraldo_project = Project.create(name: "Witchcraft?", description: "histroy of witchcraft and other assorted occupations in early modern europe", user: geraldo)
egg_project = Project.create(name: "Egg Eggerson's Eggcellent Egg Eggxamples", description: "papers about eggs", user: egg)


Article.create(title: "Type analysis for JavaScript", authors: "SH Jensen, A Møller, P Thiemann", language: "English", keywords: "javascript, types", content: "https://cs.au.dk/~amoeller/papers/tajs/paper.pdf", flagged: true, description:"JavaScript is the main scripting language for Web browsers, and it is essential to modern Web applications. Programmers have started using it for writing complex applications, but there is still little tool support available during development. We present a static program …", project: javascript_project) 
Article.create(title: "The essence of JavaScript", authors: "A Guha, C Saftoiu, S Krishnamurthi", language: "Javascript", keywords: "javascript", content: "https://arxiv.org/pdf/1510.00925", flagged: true, description:"We reduce JavaScript to a core calculus structured as a small-step operational semantics. We present several peculiarities of the language and show that our calculus models them. We explicate the desugaring process that turns JavaScript programs into ones in the core …", project: javascript_project) 
Article.create(title: "What is eSports and why do people watch it?", authors: "J Hamari, M Sjöblom", language: "English", keywords: "esports", content: "https://trepo.tuni.fi/bitstream/handle/10024/101034/what_is_esports_and_2017.pdf?sequence=1&isAllowed=y", flagged: false, description:"The purpose of this paper is to investigate why do people spectate eSports on the internet. The authors define eSports (electronic sports) as “a form of sports where the primary aspects of the sport are facilitated by electronic systems; the input of players and …", project: javascript_project) 

Article.create(title: "Star Trek fandom as a religious phenomenon", authors: "M Jindra", language: "English", keywords: "star trek, religion", content: "https://www.academia.edu/download/34359763/STFandom_article_Jindra_SOR.pdf", flagged: true, description:"This essay is an ethnographic exploration of Star Trek fandom. Rather than the more common textual analyses of the program, this article examines the history and practice of the fans themselves, on computer networks, at conventions and in tourism, in “Starfleet” fan …", project: spock_project) 
Article.create(title: "Going cultural: Star Trek, state action, and popular culture", authors: "J Weldes", language: "English", keywords: "star trek, popular culture, the state", content: "https://www.researchgate.net/profile/Jutta_Weldes/publication/224862176_Going_Cultural_Star_Trek_State_Action_and_Popular_Culture/links/5714caa408ae8b02e65df5ea.pdf", flagged: false, description:"Since the end of the cold war, international relations has witnessed the 'return of culture'in a least two forms.' Culture has reemerged, first, as a source of insecurity in the international system. Samuel Huntington's notorious warning about an impending 'clash of civilisations' ",  project: spock_project) 
Article.create(title: "A history of astronomy", authors: "A Pannekoek", language: "English", keywords: "astronomy, history", content: "https://www.aaap.be/Pdf/Anton-Pannekoek/Pannekoek-en-1989-A-History-Of-Astronomy-01.pdf", flagged: false, description: "Well-balanced, carefully reasoned study relates astronomy to political, social conditions of the day. Part I covers ancient astronomy, including Ptolemaic theory; Part II discusses Copernicus, Kepler, Newton, laws of celestial mechanics. Part III covers modern …", project: spock_project) 
Article.create(title: "Fundamental astronomy", authors: "H Karttunen, P Kröger, H Oja, M Poutanen, KJ Donner", language: "English", keywords: "astronomy, fundementals", content: "http://eprints.ukh.ac.id/id/eprint/257/1/2017_Book_FundamentalAstronomy.pdf", flagged: true, description:"Fundamental Astronomy gives a well-balanced and comprehensive introduction to the topics of classical and modern astronomy. While emphasizing both the astronomical concepts and the underlying physical principles, the text provides a sound basis for more …", project: spock_project) 

Article.create(title: "The History of the Battle of Agincourt: And of the Expedition of Henry the Fifth Into France; to which is Added, the Roll of the Men at Arms, in the English Army", authors: "NH Nicolas", language: "English", keywords: "agincourt, englihs army", content: "https://books.google.com/books?hl=en&lr=&id=kbgaAAAAYAAJ&oi=fnd&pg=PR1&dq=battle+of+agincourt&ots=lSC1tAN2Jj&sig=DeNnLDkC1a-HF0_AjdxaApsDusk", flagged: true, description:"STORY OF THE BATTLE OF AGINCOURT could scarcely be prefixed to it without conveying a tacit but severe reflection on the literary taste of the age, for if there be a subject that ought in an eminent degree to excite attention, it is a detailed account of an event which is identified …", project: boromir_project) 
Article.create(title: "The Battle of Agincourt: An Alternative Location?", authors: "T Sutherland", language: "English", keywords: "agincourt, location", content: "https://www.academia.edu/download/31545774/Battle_Agincourt_Alternative_Location_Published__version_244-263.pdf", flagged: false, description:"The recent publicity surrounding the proposed construction of a wind farm close to the Medieval Agincourt battlefield in France has provoked an outcry suggesting that, once again, a European historic battlefield is at risk. A recent archaeological survey on the …", project: boromir_project) 
Article.create(title: "A Lying Legacy? A Preliminary Discussion of Images of Antiquity and Altered Reality in Medieval Military History", authors: "R Abels, S Morillo", language: "English", keywords: "medieval, military history", content: "https://www.academia.edu/download/2008505/Morillo_Lying_Legacy.pdf", flagged: true, description: "In 1990 one of the co-authors of this article, Richard Abels, was asked by Donald Scragg to contribute a chapter on late tenth-and early eleventh-century English tactics and strategy to a volume of essays marking the millennium of the battle of Maldon. He agreed readily …", project: boromir_project) 

Article.create(title: "Guide to the Names in The Lord of the Rings", authors: "JRR Tolkien", language: "English", keywords: "lotr, names", content: "http://www.tolkien.ro/text/JRR%20Tolkien%20-%20Guide%20to%20the%20Names%20in%20The%20Lord%20of%20the%20Rings.pdf", flagged: true, description:"These Notes on Nomenclature were made by JRR Tolkien to assist translators of the book into other languages. They were composed when only the Swedish and Dutch translations had appeared. They have been revised for publication by Christopher Tolkien. All …!", project: faramir_project) 
Article.create(title: "Middle‐earth Meets New Zealand: Authenticity and Location in the Making of The Lord of the Rings", authors: "D Jones, K Smith", language: "English", keywords: "lotr, film, peter jackson, new zealand", content: "https://www.academia.edu/download/50873943/j.1467-6486.2005.00527.x20161213-26558-qg9o3m.pdf", flagged: false, description:" In focusing on the making of a specific cultural project, The Lord of the Rings (LOTR) film trilogy, this paper draws out the tensions between two sometimes divergent strands of authenticity: creative authenticity and national authenticity. This study is located in …", project: faramir_project) 
Article.create(title: "JRR Tolkien, Fanfiction, and  'the Freedom of the Reader'", authors: "MB Abrahamson", language: "English", keywords: "jrrt, fanfiction", content: "http://dc.swosu.edu/cgi/viewcontent.cgi?article=1086&context=mythlore", flagged: true, description: "Abstract Student paper award, Mythcon 2013. Abrahamson makes a particularly convincing case for the validity of fanfiction by applying Tolkien's own statements about the “dominion of the author,” the “Cauldron of Story,” and subcreation to the issue. Discusses Tolkien's …", project: faramir_project) 
Article.create(title: "Critically examining the use of blog-based fanfiction in the advanced language classroom", authors: "S Sauro, B Sundmark", language: "English", keywords: "fanfiction", content: "https://www.academia.edu/download/57390836/SauroSundmarkInPressAE.pdf", flagged: false, description:"… The text required for this course, JRR Tolkien's fantasy novel The Hobbit, is also one that is … and songs, in part because these were common literary devices used by Tolkien in The … not innovate or explore fantasy and alternate scenarios in the way much popular fanfiction does …", project: faramir_project) 
Article.create(title: "Affirmational and Transformational Values and Practices in the Tolkien Fanfiction Community", authors: "DM Walls-Thumma", language: "English", keywords: "lotr, fanfiction", content: "https://scholar.valpo.edu/cgi/viewcontent.cgi?article=1150&context=journaloftolkienresearch", flagged: true, description:"… Through an extended metaphor about the “Cauldron of Story,” JRR Tolkien's 1948 essay “On Fairy-stories” presents a theory of the … responses, which included information on demographics and the views and habits of both authors and readers of Tolkien-based fanfiction …", project: faramir_project) 
Article.create(title: "Fanfiction and the author: How fanfic changes popular cultural texts", authors: "J Fathallah", language: "English", keywords: "fanfic, cultraul texts", content: "https://library.oapen.org/bitstream/handle/20.500.12657/25984/1004097.pdf?sequence=1", flagged: true, description:"Through a rigorous quantitative/qualitative discourse analysis-never before undertaken in relation to online fanfiction and its reception-Fanfiction and the Author demonstrates how fanfic relating to Sherlock, Game of Thrones and Supernatural works to change and …", project: faramir_project) 

# Article.create(title: "Oedipus and the devil: witchcraft, religion and sexuality in early modern Europe", authors: "L Roper", language: "English", keywords: "withcraft, sexuality", content: "http://courses.washington.edu/hsteu305/Roper%20WC%20and%20Fantasy.PDF", flagged: true, description:"Cool Description Here!", project: geraldo_project) 
# Article.create(title: "Witchcraft and Gender in Early Modern Europe", authors: "A Rowlands", language: "English", keywords: "witchcraft, gender", content: "https://www.oxfordhandbooks.com/view/10.1093/oxfordhb/9780199578160.001.0001/oxfordhb-9780199578160-e-26?result=346&rskey=UhJwgJ&mediaType=Article", flagged: true, description:"Cool Description Here!", project: geraldo_project) 
# Article.create(title: "Magic and technology in early modern Europe", authors: "A Grafton", language: "English", keywords: "magic, technology, early modern europe", content: "https://repository.si.edu/bitstream/handle/10088/7193/Grafton_2002.pdf", flagged: false, description:"Cool Description Here!", project: geraldo_project) 
# Article.create(title: "Magic as a State of Mind?: Neurocognitive Theory and Magic in Early Modern Europe", authors: "J Sørensen", language: "English", keywords: "magic, neuroscience", content: "https://www.academia.edu/download/45092638/Sorensen_2010.pdf", flagged: false, description:"Cool Description Here!", project: geraldo_project)  

Article.create(title: "Molecular cooking: physical transformations in Chinese 'century' eggs", authors: "E Eiser, CS Miles, N Geerts, P Verschuren…", language: "English", keywords: "eggs", content: "https://www.researchgate.net/profile/Peter_Verschuren/publication/248842695_Molecular_cooking_Physical_transformations_in_Chinese_%27century%27_eggs/links/551d25680cf23e2801fe0326.pdf", flagged: true, description: "Over two thousand years ago the Chinese developed a method to preserve eggs such that they remain edible for many months. The room temperature, physico-chemical preservation process that is used to prepare 'century'eggs transforms the egg white into a yellow …", project: egg_project)  
Article.create(title: "Peelability of hard-cooked eggs", authors: "GW Fullter, P Angus- Poultry Science, 1969, Elsevier", language: "English", keywords: "eggs", content: "https://www.sciencedirect.com/science/article/pii/S0032579119530589/pdf?md5=aca25c954b8769dc6634c6cda9af6920&pid=1-s2.0-S0032579119530589-main.pdf", flagged: false, description: "DIFFICULTIES in peeling hard-cooked eggs cleanly, without nicking or scoring the surface of the cooked white, have plagued salad makers. Substantial losses of edible product are encountered when large pieces of cooked white adhere firmly to the shell and membranes …",project: egg_project)  
Article.create(title: "Hard-cooking and pickling eggs as teaching aids", authors: "AJ Maurer", language: "English", keywords: "eggs", content: "https://www.sciencedirect.com/science/article/pii/S0032579119553597/pdf?md5=679e3788fa564e5952a441be18549339&pid=1-s2.0-S0032579119553597-main.pdf", flagged: true, description: "A single laboratory experiment was used to teach several egg-use and preservation practices. Students in a poultry products technology class were asked to hard-cook eggs, observing the effect of age of eggs, shell piercing, initial egg temperature, starting water …", project: egg_project)  